Script started on 2020-02-12 15:53:11-0500
]0;sp46@gold11: ~/214/labs/02[01;32msp46@gold11[00m:[01;34m~/214/labs/02[00m$ cat example6.lex example6.y
%{
#include <stdio.h>
#include <stdlib.h>           /* atoi() */
#include <string.h>           /* strcmp() */
#include "example6.tab.h"
%}
%%
[0-9]+                  yylval = atoi(yytext); return NUMBER;
heat                    return TOKHEAT;
on|off                  yylval = !strcmp(yytext,"on"); return STATE;
set                     return TOKSET;
temperature             return TOKTEMPERATURE;
humidity 		return TOKHUMIDITY;
\n                      /* ignore end of line */;
[ \t]+                  /* ignore whitespace */;
%%


    %{
    #include <stdio.h>
    #include <string.h>

    /* declarations */
    int yylex (void);
    void yyerror (char const *);
    int yyparse(void);


    /* definitions */ 
    void yyerror(const char *str) {
            fprintf(stderr,"error: %s\n",str);
    }
     
    int yywrap() {
            return 1;
    } 
     
    int main() {
            yyparse();
    } 

    %}

    %token NUMBER TOKHEAT STATE TOKSET TOKTEMPERATURE TOKHUMIDITY
    %%

commands: /* empty */
        | commands command
        ;

command:
        heat_switch
        | temperature_set
	| humidity_set
        ;

heat_switch:
        TOKHEAT STATE
        {
        	if ($2) {  /* if STATE == 1 */
                        printf("\tHeat turned on\n");
                } else {
                        printf("\tHeat turned off\n");
                }   
	}
        ;

temperature_set:
        TOKSET TOKTEMPERATURE NUMBER
        {
                printf("\tTemperature set to %d\n", $3);
        }
        ;

humidity_set:
        TOKSET TOKHUMIDITY NUMBER
        {
                printf("\tHumidity set to %d\n", $3);
        }
        ;]0;sp46@gold11: ~/214/labs/02[01;32msp46@gold11[00m:[01;34m~/214/labs/02[00m$ make
make: 'example6' is up to date.
]0;sp46@gold11: ~/214/labs/02[01;32msp46@gold11[00m:[01;34m~/214/labs/02[00m$ flx ex example6.lex
]0;sp46@gold11: ~/214/labs/02[01;32msp46@gold11[00m:[01;34m~/214/labs/02[00m$ bison -d xam   example4.y   6.y
]0;sp46@gold11: ~/214/labs/02[01;32msp46@gold11[00m:[01;34m~/214/labs/02[00m$ gcc lex.yy.c xa  example6.tab.c -o ecx  xample6
]0;sp46@gold11: ~/214/labs/02[01;32msp46@gold11[00m:[01;34m~/214/labs/02[00m$ ./example6
heat on
	Heat turned on
heat off
	Heat turned off
set temperature 92
	Temperature set to 92
set temperature 0
	Temperature set to 0
set tem   humidit  y 8
	Humidity set to 8
set humidity 92
	Humidity set to 92
heat off
	Heat turned off
]0;sp46@gold11: ~/214/labs/02[01;32msp46@gold11[00m:[01;34m~/214/labs/02[00m$ exit
