Script started on 2020-03-05 10:23:18-0500
]0;sp46@gold10: ~/214/labs/extraCredit[01;32msp46@gold10[00m:[01;34m~/214/labs/extraCredit[00m$ clojure
Clojure 1.10.1
user=> (fn [x] (+ x x))
#object[user$eval136$fn__137 0x6d467c87 "user$eval136$fn__137@6d467c87"]
user=> ((fn [x] (+ x x )) 21)
42
user=> ^[[A^[[B        ((fn [x y] (+ (* x x) (* y y))) 3 4)
25
user=> 
]0;sp46@gold10: ~/214/labs/extraCredit[01;32msp46@gold10[00m:[01;34m~/214/labs/extraCredit[00m$ exit

Script done on 2020-03-05 10:24:02-0500
